"""Initial migration

Revision ID: 84d4d3fed9ca
Revises: 
Create Date: 2025-11-01 12:01:45.698696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84d4d3fed9ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('water_goal', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('calorie_goal', sa.Integer(), nullable=True),
    sa.Column('sleep_goal', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('feeling', sa.Integer(), nullable=True),
    sa.Column('effort_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('llm_advice', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_days_date'), 'days', ['date'], unique=False)
    op.create_index(op.f('ix_days_id'), 'days', ['id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_status'), 'goals', ['status'], unique=False)
    op.create_index(op.f('ix_goals_type'), 'goals', ['type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('calories_burned', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('heart_rate_avg', sa.Integer(), nullable=True),
    sa.Column('heart_rate_max', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_type'), 'exercises', ['type'], unique=False)
    op.create_table('llm_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('effort_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('score_reason', sa.Text(), nullable=True),
    sa.Column('nutrition_analysis', sa.Text(), nullable=True),
    sa.Column('exercise_analysis', sa.Text(), nullable=True),
    sa.Column('sleep_analysis', sa.Text(), nullable=True),
    sa.Column('mood_analysis', sa.Text(), nullable=True),
    sa.Column('tomorrow_advice', sa.Text(), nullable=True),
    sa.Column('weekly_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('generation_time', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_id')
    )
    op.create_index(op.f('ix_llm_summaries_created_at'), 'llm_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_summaries_id'), 'llm_summaries', ['id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sugar', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sodium', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_suggestions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_category'), 'meals', ['category'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_table('mood_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('anxiety_level', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=50), nullable=True),
    sa.Column('ai_suggestions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mood_records_id'), 'mood_records', ['id'], unique=False)
    op.create_index(op.f('ix_mood_records_time'), 'mood_records', ['time'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('sleep_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('bedtime', sa.DateTime(), nullable=True),
    sa.Column('wake_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('deep_sleep', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('rem_sleep', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('interruptions', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=True),
    sa.Column('ai_recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sleep_records_id'), 'sleep_records', ['id'], unique=False)
    op.create_table('water_intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_intakes_id'), 'water_intakes', ['id'], unique=False)
    op.create_index(op.f('ix_water_intakes_time'), 'water_intakes', ['time'], unique=False)
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_sets_id'), 'exercise_sets', ['id'], unique=False)
    op.create_table('meal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_id'), 'meal_items', ['id'], unique=False)
    op.create_index(op.f('ix_meal_items_name'), 'meal_items', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_items_name'), table_name='meal_items')
    op.drop_index(op.f('ix_meal_items_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_index(op.f('ix_exercise_sets_id'), table_name='exercise_sets')
    op.drop_table('exercise_sets')
    op.drop_index(op.f('ix_water_intakes_time'), table_name='water_intakes')
    op.drop_index(op.f('ix_water_intakes_id'), table_name='water_intakes')
    op.drop_table('water_intakes')
    op.drop_index(op.f('ix_sleep_records_id'), table_name='sleep_records')
    op.drop_table('sleep_records')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_mood_records_time'), table_name='mood_records')
    op.drop_index(op.f('ix_mood_records_id'), table_name='mood_records')
    op.drop_table('mood_records')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_category'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_llm_summaries_id'), table_name='llm_summaries')
    op.drop_index(op.f('ix_llm_summaries_created_at'), table_name='llm_summaries')
    op.drop_table('llm_summaries')
    op.drop_index(op.f('ix_exercises_type'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_goals_type'), table_name='goals')
    op.drop_index(op.f('ix_goals_status'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_days_id'), table_name='days')
    op.drop_index(op.f('ix_days_date'), table_name='days')
    op.drop_table('days')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
